services:
  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8000:8000"
  customers_service:
    build:
      context: ./customers_service
    ports:
      - "8001:8000"
  inventory_service:
    build:
      context: ./inventory_service
    ports:
      - "8002:8000"
  review_service:
    build:
      context: ./review_service
    ports:
      - "8003:8000"